# Generated by Django 2.0.6 on 2018-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('cantidad', models.FloatField()),
                ('calorias', models.FloatField()),
                ('azucar', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default=None, max_length=15)),
                ('sal', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default=None, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('preparación', models.CharField(max_length=500)),
                ('tiempoComida', models.CharField(choices=[('Snack', 'Snack'), ('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], default=None, max_length=15)),
                ('ingredientes', models.ManyToManyField(to='dieta.Ingrediente')),
            ],
        ),
    ]
