# Generated by Django 2.0.6 on 2018-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='nomIngrediente',
            field=models.CharField(default='', max_length=60),
        ),
    ]
