# Generated by Django 2.0.6 on 2018-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0003_auto_20181124_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.CharField(max_length=30),
        ),
    ]
