# Generated by Django 2.0.6 on 2018-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0004_auto_20181124_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='Vegetariana',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='plato',
            name='tipoDieta',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
