# Generated by Django 2.0.6 on 2018-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0005_auto_20181124_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='Vegetariana',
            new_name='vegetariano',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='azucar',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='calorias',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='sal',
        ),
        migrations.AddField(
            model_name='plato',
            name='azucar',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='plato',
            name='dietaCal',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='plato',
            name='sal',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default=None, max_length=15),
        ),
    ]
