# Generated by Django 2.0.6 on 2018-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0007_remove_plato_vegetariano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nomIngrediente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plato',
            name='dietaCal',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='plato',
            name='preparación',
            field=models.CharField(max_length=600),
        ),
    ]
