# Generated by Django 2.0.6 on 2018-11-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0008_auto_20181126_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='preparación',
            new_name='preparacion',
        ),
    ]
